version: '3.9'
services:
  db:
    container_name: pipeline-teamcity-db
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - /root/postgres/data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=GMT+8
      - ./01-init-db.sh:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - teamcity-network

  server:
    container_name: pipeline-teamcity-server
    image: jetbrains/teamcity-server:latest
    privileged: true
    user: root
    ports:
      - 8111:8111
    volumes:
      - /root/teamcity_server/data:/data/teamcity_server/datadir
      - /root/teamcity_server/logs:/opt/teamcity/logs
    restart: unless-stopped
    networks:
      - teamcity-network
    depends_on:
      - db

  agent:
    container_name: pipeline-teamcity-agent-alpha
    image: jetbrains/teamcity-agent:latest
    privileged: true
    user: root
    volumes:
      - /root/teamcity_agents/alpha/conf:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=pipeline-teamcity-server:8111
      - AGENT_NAME=alpha
    restart: unless-stopped
    networks:
      - teamcity-network
    depends_on:
      - db

  sonarqube:
    container_name: pipeline-sonarqube
    image: sonarqube:latest
    privileged: true
    user: root
    volumes:
      - /root/sonarqube/data:/opt/sonarqube/data
      - /root/sonarqube/extensions:/opt/sonarqube/extensions
      - /root/sonarqube/logs:/opt/sonarqube/logs
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonar
      - SONARQUBE_JDBC_USERNAME=${POSTGRES_USER}
      - SONARQUBE_JDBC_PASSWORD=${POSTGRES_PASSWORD}
      - SONAR_WEB_PORT=9000
    ports:
      - 9000:9000
    networks:
      - teamcity-network
    depends_on:
      - db

networks:
  teamcity-network:
